services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      mysql_db:
        condition: service_healthy

  frontend:
    build:
      context: ./qcmplusweb
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mysql_db:
    image: mysql:8.0.37-debian
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
